apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: "hello"
  labels:
    appName: hello
    appNameVersion: "hello-latest"
spec:
  replicas: 3
  selector:
    matchLabels:
      appNameVersion: "hello-latest"
  template:
    metadata:
      labels:
        appName: hello
        appNameVersion: "hello-latest"
    spec:
      restartPolicy: Always
      containers:
        - name: hello
          image: "registry.cn-shanghai.aliyuncs.com/helphands/helphands-impl:latest"
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: KAFKA_SERVICE
              value: "kafka"
#            - name: "RP_APP_NAME"
#              value: hello
#            - name: "RP_APP_TYPE"
#              value: lagom
#            - name: "RP_APP_VERSION"
#              value: "1.0-SNAPSHOT"
#            - name: "RP_ENDPOINTS"
#              value: "HTTP,AKKA_REMOTE,AKKA_MGMT_HTTP"
#            - name: "RP_ENDPOINTS_COUNT"
#              value: "3"
#            - name: "RP_ENDPOINT_0_BIND_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_0_BIND_PORT"
#              value: "10000"
#            - name: "RP_ENDPOINT_0_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_0_PORT"
#              value: "10000"
#            - name: "RP_ENDPOINT_1_BIND_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_1_BIND_PORT"
#              value: "10001"
#            - name: "RP_ENDPOINT_1_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_1_PORT"
#              value: "10001"
#            - name: "RP_ENDPOINT_2_BIND_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_2_BIND_PORT"
#              value: "10002"
#            - name: "RP_ENDPOINT_2_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_2_PORT"
#              value: "10002"
#            - name: "RP_ENDPOINT_AKKA_MGMT_HTTP_BIND_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_AKKA_MGMT_HTTP_BIND_PORT"
#              value: "10002"
#            - name: "RP_ENDPOINT_AKKA_MGMT_HTTP_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_AKKA_MGMT_HTTP_PORT"
#              value: "10002"
#            - name: "RP_ENDPOINT_AKKA_REMOTE_BIND_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_AKKA_REMOTE_BIND_PORT"
#              value: "10001"
#            - name: "RP_ENDPOINT_AKKA_REMOTE_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_AKKA_REMOTE_PORT"
#              value: "10001"
#            - name: "RP_ENDPOINT_HTTP_BIND_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_HTTP_BIND_PORT"
#              value: "10000"
#            - name: "RP_ENDPOINT_HTTP_HOST"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_ENDPOINT_HTTP_PORT"
#              value: "10000"
#            - name: "RP_KUBERNETES_POD_IP"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "status.podIP"
#            - name: "RP_KUBERNETES_POD_NAME"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "metadata.name"
#            - name: "RP_MODULES"
#              value: "akka-cluster-bootstrapping,akka-management,common,play-http-binding,service-discovery,status"
#            - name: "RP_NAMESPACE"
#              valueFrom:
#                fieldRef:
#                  fieldPath: "metadata.namespace"
#            - name: "RP_PLATFORM"
#              value: kubernetes
#            - name: "RP_APPLICATION_SECRET"
#              value: "change-this"
#            - name: "RP_CASSANDRA_URL"
#              value: "_cql._tcp.reactive-sandbox-cassandra.default.svc.cluster.local"
#            - name: "RP_KAFKA_URL"
#              value: "_broker._tcp.reactive-sandbox-kafka.default.svc.cluster.local"
#            - name: "JAVA_OPTS"
#              value: "-Xms128m -Xmx256m -Dconfig.resource=prod-application.conf -Dplay.http.secret.key=$(RP_APPLICATION_SECRET) -Dcom.lightbend.platform-tooling.service-discovery.external-service-addresses.cas_native.0=$(RP_CASSANDRA_URL) -Dcom.lightbend.platform-tooling.service-discovery.external-service-addresses.kafka_native.0=$(RP_KAFKA_URL)"
          ports:
            - containerPort: 10000
              name: http
            - containerPort: 10001
              name: "akka-remote"
            - containerPort: 10002
              name: "akka-mgmt-http"
          volumeMounts: []
          readinessProbe:
            httpGet:
              path: "/platform-tooling/ready"
              port: "akka-mgmt-http"
            periodSeconds: 10
            initialDelaySeconds: 180
          livenessProbe:
            httpGet:
              path: "/platform-tooling/healthy"
              port: "akka-mgmt-http"
            periodSeconds: 10
            initialDelaySeconds: 120
          resources:
            limits:
              cpu: 0.15
              memory: 512Mi
            requests:
              cpu: 0.15
              memory: 512Mi
      volumes: []

---

apiVersion: v1
kind: Service
metadata:
  labels:
    appName: hello
  name: hello
spec:
  ports:
    - name: http
      port: 10000
      protocol: TCP
      targetPort: 10000
    - name: "akka-remote"
      port: 10001
      protocol: TCP
      targetPort: 10001
    - name: "akka-mgmt-http"
      port: 10002
      protocol: TCP
      targetPort: 10002
  selector:
    appName: hello